project:
  type: website
  output-dir: _docs
  render:
    - "*.qmd"
    - "!drafts/"

website:
  title: "zakki6"
  navbar:
    aria-label: Main navigation
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Contents（qmd）
        menu:
          - href: notes/note01.qmd
            text: note01 - OGP
    right:
      - href: https://github.com/watanabe3tipapa/zakki6
        text: Source Code
        icon: github

format:
  html:
    theme: spacelab
    toc: true
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: false
  error: false
  cache: true

freeze: auto

resources:
  - CNAME
  - .nojekyll

editor: visual